import math

MAP_SIZE = 100
OBSTACLE_RADIUS = 3
OBSTACLE_SPEED = 1
DIAGONAL_COST = math.sqrt(2)
STRAIGHT_COST = 1
ATTRACTIVE_WEIGHT = 1.0
REPULSIVE_WEIGHT = 200.0
INFLUENCE_RADIUS = 13
NUM_UAVS = 4
FORMATION_SPACING = 10
DISPERSION_DISTANCE = 4
UAV_RADIUS = 1
MAX_STEP_SIZE = 2.0
MIN_SPEED_THRESHOLD = 0.1
FORMATION_THRESHOLD = 1.5
OBSTACLE_AVOIDANCE_THRESHOLD = 13
REPLAN_INTERVAL = 10
MIN_FORCE_THRESHOLD = 0.1  # 力平衡检测阈值
ESCAPE_DISTANCE = 5.0  # 摆脱平衡时的位移距离